version: '2.2'

networks:
  etsi-network:
    driver: bridge

services:
  # Orderer 1
  orderer1.etsi.com:
    container_name: orderer1.etsi.com
    image: hyperledger/fabric-orderer:2.4.1
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_CLUSTER_LISTENPORT=7051
      - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer1.etsi.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer1.etsi.com/tls:/var/hyperledger/orderer/tls
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    networks:
      - etsi-network

  # Orderer 2
  orderer2.etsi.com:
    container_name: orderer2.etsi.com
    image: hyperledger/fabric-orderer:2.4.1
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_CLUSTER_LISTENPORT=8051
      - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer2.etsi.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer2.etsi.com/tls:/var/hyperledger/orderer/tls
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 8050:8050
    networks:
      - etsi-network

  # Orderer 3
  orderer3.etsi.com:
    container_name: orderer3.etsi.com
    image: hyperledger/fabric-orderer:2.4.1
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_CLUSTER_LISTENPORT=9051
      - ORDERER_GENERAL_CLUSTER_SERVERCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_SERVERPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer3.etsi.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/etsi.com/orderers/orderer3.etsi.com/tls:/var/hyperledger/orderer/tls
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 9050:9050
    networks:
      - etsi-network

  # CouchDB
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.2.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - etsi-network

  # CLI tools
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.4.1
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ../crypto-config:/etc/hyperledger/fabric/crypto-config
      - ../channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - ../chaincode:/opt/gopath/src/github.com/chaincode
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    networks:
      - etsi-network
